apiVersion: apps/v1
kind: Deployment
metadata:
  name: admin-deployment
  namespace: food
spec:
  replicas: 1
  selector:
    matchLabels:
      app: admin
  template:
    metadata:
      labels:
        app: admin
      annotations:
        ci.github.com/revision: 265982f9c94b75776e4460cc7bd88f9c8560050b
    spec:
      containers:
        - name: admin
          image: 841702866815.dkr.ecr.ap-south-1.amazonaws.com/food-delivery-admin:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
