apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  namespace: food

spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend

  template:
    metadata:
      labels:
        app: frontend

    spec:
      containers:
      - name: frontend
        image: 841702866815.dkr.ecr.ap-south-1.amazonaws.com/food-delivery-frontend:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 80

        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "200m"
            memory: "256Mi"





