name: CI/CD Pipeline

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'

  pull_request:
    branches:
      - main
    paths-ignore:
      - 'k8s/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: read
  pull-requests: read

env:
  AWS_REGION: ap-south-1

  ECR_BACKEND: food-delivery-backend
  ECR_FRONTEND: food-delivery-frontend
  ECR_ADMIN: food-delivery-admin

  IMAGE_TAG: latest

jobs:

  # =========================================================
  # SONARQUBE
  # =========================================================

  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.2.2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: https://sonarcloud.io
        with:
          args: >
            -Dsonar.projectKey=food-app
            -Dsonar.organization=nevil18
  # =========================================================
  # OWASP DEPENDENCY CHECK
  # =========================================================

  owasp:
    name: OWASP Dependency Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: food-delivery-app
          path: .
          format: HTML
          out: reports
          args: >
            --failOnCVSS 7
            --enableRetired
            --disableAssembly
      - name: Upload OWASP report
        uses: actions/upload-artifact@v7
        if: always()
        with:
          name: owasp-dependency-report
          path: reports/
          if-no-files-found: warn


  # =========================================================
  # DETECT CHANGED SERVICES
  # =========================================================

  changes:
    name: Detect Changed Services
    runs-on: ubuntu-latest

    outputs:
      backend: ${{ steps.filter.outputs.backend }}
      frontend: ${{ steps.filter.outputs.frontend }}
      admin: ${{ steps.filter.outputs.admin }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Detect changed paths
        id: filter
        uses: dorny/paths-filter@v4
        with:
          filters: |
            backend:
              - 'backend/**'
            frontend:
              - 'frontend/**'
            admin:
              - 'admin/**'
  # =========================================================
  # BACKEND
  # =========================================================

  backend:
    name: Backend Build + Trivy + ECR
    runs-on: ubuntu-latest

    needs:
      - sonarqube
      - owasp
      - changes

    if: needs.changes.outputs.backend == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build backend Docker image
        run: |
          docker build \
            --pull \
            --no-cache \
            -t food-backend:${IMAGE_TAG} \
            backend/
      - name: Trivy scan backend
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: food-backend:latest
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          vuln-type: os,library

      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag backend image for ECR
        if: github.event_name == 'push'
        run: |
          docker tag \
            food-backend:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_BACKEND }}:latest
      - name: Push backend image to ECR
        if: github.event_name == 'push'
        run: |
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_BACKEND }}:latest
  # =========================================================
  # FRONTEND
  # =========================================================

  frontend:
    name: Frontend Build + Trivy + ECR
    runs-on: ubuntu-latest

    needs:
      - sonarqube
      - owasp
      - changes

    if: needs.changes.outputs.frontend == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build frontend Docker image
        run: |
          docker build \
            --pull \
            --no-cache \
            -t food-frontend:${IMAGE_TAG} \
            frontend/
      - name: Trivy scan frontend
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: food-frontend:latest
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          vuln-type: os,library

      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag frontend image for ECR
        if: github.event_name == 'push'
        run: |
          docker tag \
            food-frontend:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_FRONTEND }}:latest
      - name: Push frontend image to ECR
        if: github.event_name == 'push'
        run: |
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_FRONTEND }}:latest
  # =========================================================
  # ADMIN
  # =========================================================

  admin:
    name: Admin Build + Trivy + ECR
    runs-on: ubuntu-latest

    needs:
      - sonarqube
      - owasp
      - changes

    if: needs.changes.outputs.admin == 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Build admin Docker image
        run: |
          docker build \
            --pull \
            --no-cache \
            -t food-admin:${IMAGE_TAG} \
            admin/
      - name: Trivy scan admin
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          image-ref: food-admin:latest
          format: table
          exit-code: '1'
          ignore-unfixed: true
          severity: CRITICAL,HIGH
          vuln-type: os,library
          trivyignores: admin/.trivyignore
      - name: Configure AWS credentials
        if: github.event_name == 'push'
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        if: github.event_name == 'push'
        uses: aws-actions/amazon-ecr-login@v2

      - name: Tag admin image for ECR
        if: github.event_name == 'push'
        run: |
          docker tag \
            food-admin:latest \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_ADMIN }}:latest
      - name: Push admin image to ECR
        if: github.event_name == 'push'
        run: |
          docker push \
            ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/${{ env.ECR_ADMIN }}:latest
  # =========================================================
  # UPDATE KUBERNETES
  # =========================================================

  update-k8s:
    name: Update Kubernetes Images
    runs-on: ubuntu-latest

    needs:
      - changes
      - backend
      - frontend
      - admin

    if: |
      always() &&
      github.event_name == 'push' &&
      github.ref == 'refs/heads/main' &&
      (
        needs.changes.outputs.backend != 'true' ||
        needs.backend.result == 'success'
      ) &&
      (
        needs.changes.outputs.frontend != 'true' ||
        needs.frontend.result == 'success'
      ) &&
      (
        needs.changes.outputs.admin != 'true' ||
        needs.admin.result == 'success'
      ) &&
      (
        needs.changes.outputs.backend == 'true' ||
        needs.changes.outputs.frontend == 'true' ||
        needs.changes.outputs.admin == 'true'
      )
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: Install yq
        run: |
          sudo wget -q \
            https://github.com/mikefarah/yq/releases/download/v4.53.6/yq_linux_amd64 \
            -O /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq
          yq --version
      - name: Update Kubernetes image tags
        env:
          ACCOUNT: ${{ secrets.AWS_ACCOUNT_ID }}
          REGION: ${{ env.AWS_REGION }}
          BACKEND_CHANGED: ${{ needs.changes.outputs.backend }}
          FRONTEND_CHANGED: ${{ needs.changes.outputs.frontend }}
          ADMIN_CHANGED: ${{ needs.changes.outputs.admin }}
          GITHUB_SHA_VALUE: ${{ github.sha }}

        run: |
          if [ "$BACKEND_CHANGED" = "true" ]; then
            echo "Updating backend..."
            yq -i \
              '.spec.template.spec.containers[].image = strenv(ACCOUNT) + ".dkr.ecr." + strenv(REGION) + ".amazonaws.com/food-delivery-backend:latest"' \
              k8s/backend_deployment.yml
            yq -i \
              '.spec.template.metadata.annotations."ci.github.com/revision" = strenv(GITHUB_SHA_VALUE)' \
              k8s/backend_deployment.yml
          fi
          if [ "$FRONTEND_CHANGED" = "true" ]; then
            echo "Updating frontend..."
            yq -i \
              '.spec.template.spec.containers[].image = strenv(ACCOUNT) + ".dkr.ecr." + strenv(REGION) + ".amazonaws.com/food-delivery-frontend:latest"' \
              k8s/frontend_deployment.yml
            yq -i \
              '.spec.template.metadata.annotations."ci.github.com/revision" = strenv(GITHUB_SHA_VALUE)' \
              k8s/frontend_deployment.yml
          fi
          if [ "$ADMIN_CHANGED" = "true" ]; then
            echo "Updating admin..."
            yq -i \
              '.spec.template.spec.containers[].image = strenv(ACCOUNT) + ".dkr.ecr." + strenv(REGION) + ".amazonaws.com/food-delivery-admin:latest"' \
              k8s/admin_deployment.yml
            yq -i \
              '.spec.template.metadata.annotations."ci.github.com/revision" = strenv(GITHUB_SHA_VALUE)' \
              k8s/admin_deployment.yml
          fi
      - name: Show Kubernetes changes
        run: |
          git diff -- k8s/
      - name: Commit Kubernetes changes
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add k8s/
          if git diff --staged --quiet; then
            echo "No Kubernetes manifest changes."
          else
            git commit \
              -m "ci: deploy latest images ${GITHUB_SHA}"
            git push
          fi
